language: node_js
node_js:
  - node
before_install:
  - npm i -g npm@6.9.0
deploy:
  provider: heroku
  api_key:
    secure: R0ojqC6ofRGVFHSTaTcWPx7X8Ssxdrwxf1s5tg9nUK2ZuaPMDchkEzxt+Ky7ZQP0KU2TZdNXyGcJXYEAk+aJUWLlWYe+Od8bB9hl46mJVhgk8SGJgIxOP61Jp6WPpUerFeApjbE+ErQy+56dPzKT4tpEUP3ngTBlSNgETjF5GAuxuu+8mwVqUc6Flcrdp3aq4drPDF4zm9BT15xAeIQ8NhsOgs/vDLD/sOS7ys+jOVYSdwGGe0D68Mw8ppxSaY5y+h3dTmkcLSgGIJ3t3r15somKwoLVjiYE5mBE/8B6IkFGlpLI7JFX0n52EwPA4zoEyQisS6E33bf7S2wEfTqYhQtQcdaqHCtO/5hk8UE+biikHgU7HW3KFThbRb1loDzMVMrXmz3mfTmLq+5zY/a/GTLAe2zMY8XRUq+N9MiYZaYpkbgUDaz68a+xYSa06Wlv9urgJTbJCGYLggrsZhlRAMea42k6acRHxLBwafr1U0QGh+m0tgO08ApEBKESBusTmK+aVxpu1zPtkySFnIDyjuIv5MpzYP2BLarXuKUPCl1VJgsL8Ph/3RuAd63UR2n5v8kWx1vzO4IDI8ndj7oYakfsFN3eRq+ODJ9GOYQ/WTsayZPzHp8S1zfAt44P/W6P4nqA7wcVzbtBGL2nEXjjZ4QPn3KgRRrywAOYdK2fpGY=
  app: appkeep
