language: node_js
node_js:
- node
before_install:
- npm i -g npm@6.9.0
script:
- npm run lint
- npm run test:ci
deploy:
  provider: heroku
  api_key:
    secure: kyRdlydP0kBlyzKTQg18jD4Hw9vdeKHuOB1CFBFhVmMmmDwwdIFCYW3xYuEiw6gm7xApx8aTsoMOJOP4W583+75WgXU2xaFiieq+j4VwxIAmS7yM3ggLMGauXJwR7vv/8imM5UBcskf0CmpMBpTrR1yW36E7+c/jDl1smOHCgbGJeMXv8cm8tRERJ9F9sV4AehF7OdfDOU0A1hhoAwOyynXMFj8f6GpkiFWjywPdOOh2dw/Pe+pfds1nBit9OwXJ6lwoNIxKbDlnJkVGh6CY963HyTIitD+q7pd8A74HL8p2R63LcO31VNwAHzPtJHuI01LyfjXes99ldvd2LKBbW4gPuatWXqYGFOo6qxUeDoEwVXZ0jRXolfIm1ZEiqmTVRbS61xsTXfy0B7s7JWb6q8xBGLVkQ2vw1r+u3aZFTDnPpXyX/Qr+s2aXmpM7sPVtlDBqFx9gA7ur8K+AcNiyFv8A4SEFwUnBQJMtvEgEHokGj269EhCmHdnHjFJ8dsE6JwLx4FNqvNCUssax3NIQ66+FuRwohmueJRHLwiWwQn0lMk+GTD8NDXSo19Da5KFSknEat78TR4ALnzO0owZCXeQ7DnKZOXCBACrKsQ7q1n/Sf6edJz4+S5hjzq8bTsFJQbH+17QmX2tGf22CQ7mN3m4qIHUPgbMOMP0nIqENTyk=
  app: appkeep
